project:
  type: website
  output-dir: docs

website:
  title: "Uppsala History of Inequality and Labour Lab"
  navbar:
    right:
        - href: index.qmd
          text: Home
        - href: contact.qmd
          text: Contact

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme: [simplex, theme.scss]
    toc: true

editor: visual

