project:
  type: website
  output-dir: docs

website:
  title: "Uppsala History of Inequality and Labour Lab"
  navbar:
    right:
      - text: Browse
        menu:
        - href: index.qmd
          text: Home
        - href: about.qmd
          text: About
        - href: published.qmd
          text: Published papers
        - href: working.qmd
          text: Working papers
        - href: databases.qmd
          text: Databases

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme: [simplex, theme.scss]
    toc: true

editor: visual

